Document: dbus-tool
Title: Debian dbus-tool Manual
Author: <insert document author here>
Abstract: This manual describes what dbus-tool is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/dbus-tool/dbus-tool.sgml.gz

Format: postscript
Files: /usr/share/doc/dbus-tool/dbus-tool.ps.gz

Format: text
Files: /usr/share/doc/dbus-tool/dbus-tool.text.gz

Format: HTML
Index: /usr/share/doc/dbus-tool/html/index.html
Files: /usr/share/doc/dbus-tool/html/*.html
